spring.application.name=SwiftCardApp
spring.datasource.url=jdbc:mysql://localhost:3306/swift_cart_db
spring.datasource.username=root
spring.datasource.password=root@2005root
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
server.port=8000